### ISSUE TITLE
Threaded rendering error with multipart cable

### ISSUE THREAD

**Issue by codewarrior0** [amadornes/MCMultiPart#34]
Placing a cable from Fluxed Redstone produces this threading-related error:

```
java.util.ConcurrentModificationException
 at com.google.common.collect.HashBiMap$Itr.checkForConcurrentModification(HashBiMap.java:339)
 at com.google.common.collect.HashBiMap$Itr.hasNext(HashBiMap.java:345)
 at reborncore.mcmultipart.multipart.MultipartContainer.getExtendedStates(MultipartContainer.java:484)
 at reborncore.mcmultipart.block.BlockMultipartContainer.getExtendedState(BlockMultipartContainer.java:399)
 at reborncore.mcmultipart.block.BlockMultipartContainer.getExtendedState(BlockMultipartContainer.java:66)
 at net.minecraft.client.renderer.BlockRendererDispatcher.func_175018_a(BlockRendererDispatcher.java:80)
 at net.minecraft.client.renderer.chunk.RenderChunk.func_178581_b(RenderChunk.java:277)
 at net.minecraft.client.renderer.chunk.ChunkRenderWorker.func_178474_a(ChunkRenderWorker.java:118)
 at net.minecraft.client.renderer.chunk.ChunkRenderWorker.run(ChunkRenderWorker.java:46)
 at java.lang.Thread.run(Thread.java:745)
```

It looks like the client or server thread changed `MultipartContainer.partMap` while the rendering thread was iterating through it?

RebornCore embeds a copy of MCMultipart that appears to correspond to 91bb73d532e78bb0a1f4b2fe8c257fe99652535f.

**Comment by amadornes** [comment]
That's... Really weird... I intentionally replace the part map instead of modifying it everywhere...
The only place where something like this may be able to happen is in readFromNBT() but that should only be called once. I'll talk to @modmuss50 and see if we can figure it out together, if not, I'll tell him to repack the pre_merge2 branch because I fixed some loading/saving related things in there a few days ago.

**Comment by AlgorithmX2** [comment]
This may or may not be related to the ChunkCache Situation I mentioned on IRC.

But Special Care should be made while rendering and getting ExtendedState to use the ChunkCache, and to not not make any non synchronized modifications.

Right now ExtendedState for Parts doesn't pass the ChunkCache, so you only have access to the ClientWorld, this can result in race conditions where TileEntities are Created out of Sync with the Client Thread for instance. I just had to fix an issue like this with C&B, which required using a new 1.10.2 method on ChunkCache to ask for TileEntities only if they exist, and not create them.

**Comment by modmuss50** [comment]
I may move back to the official MCMP, that may help out some things.

**Comment by amadornes** [comment]
Should be fixed in the latest experimental build :)
