### ISSUE TITLE
NPE when updating neighbors

### ISSUE THREAD

**Issue by raoulvdberge** [amadornes/MCMultiPart#41]
```
Caused by: java.lang.NullPointerException
    at mcmultipart.block.BlockCoverable.canConnectRedstone(BlockCoverable.java:399) ~[BlockCoverable.class:?]
    at net.minecraft.block.BlockRedstoneWire.canConnectTo(BlockRedstoneWire.java:454) ~[BlockRedstoneWire.class:?]
    at net.minecraft.block.BlockRedstoneWire.isPowerSourceAt(BlockRedstoneWire.java:431) ~[BlockRedstoneWire.class:?]
    at net.minecraft.block.BlockRedstoneWire.getWeakPower(BlockRedstoneWire.java:403) ~[BlockRedstoneWire.class:?]
    at net.minecraft.block.state.BlockStateContainer$StateImplementation.getWeakPower(BlockStateContainer.java:381) ~[BlockStateContainer$StateImplementation.class:?]
    at net.minecraft.world.World.getRedstonePower(World.java:3470) ~[World.class:?]
```

Error is in this method:

``` java
    @Override
    public final boolean canConnectRedstone(IBlockState state, IBlockAccess world, BlockPos pos, EnumFacing side) {

        if (side == null) return false;
        IMicroblockContainerTile tile = getMicroblockTile(world, pos);
        MicroblockContainer container = tile != null ? tile.getMicroblockContainer() : null;
        if (container.getPartContainer().canConnectRedstone(side)) return true;
        return canConnectRedstoneDefault(state, world, pos, side, container);
    }
```

You appear to be accessing `container` when it is null.

**Comment by raoulvdberge** [comment]
Fixed
