### ISSUE TITLE
Ghost blocks with Refined Storage (1.12.1)

### ISSUE THREAD

**Issue by Renari** [amadornes/MCMultiPart#98]
In the following image these 3 machines are connected by cables, once I tried to cover them with a cover (as shown to the left of the last machine) the blocks became invisible, retaining their collision box but you can't remove them. Attempting to place anything at this location deletes the item.

![](https://i.imgur.com/zWReuN0.png)

**Comment by amadornes** [comment]
I'm releasing an update in a few minutes. Let me know if this still happens with the new version and I'll talk to Raoul to see if we can figure it out :)

**Comment by Renari** [comment]
I'm not able to test this since the new release you put out only flags 1.12.2 as a valid version but Refined Storage doesn't have a build with 1.12.2 flagged.

**Comment by raoulvdberge** [comment]
> Refined Storage doesn't have a build with 1.12.2 flagged.

![x](https://media.giphy.com/media/3oz8xLd9DJq2l2VFtu/giphy.gif)

![x](https://raoulvdberge.com/GiFRC5)

**Comment by Renari** [comment]
Heh, so it does. I somehow overlooked it I guess. The newest release on 1.12.2 using the Chisels & Bits Diamond Bit Saw to make the cover results in a crash now. Here's the stack trace.

```
---- Minecraft Crash Report ----
// You're mean.

Time: 10/2/17 2:10 PM
Description: Unexpected error

java.lang.NullPointerException: Unexpected error
	at mcmultipart.api.multipart.MultipartHelper.getContainer(MultipartHelper.java:90)
	at mcmultipart.api.multipart.MultipartOcclusionHelper.testContainerBoxIntersection(MultipartOcclusionHelper.java:33)
	at mcmultipart.api.multipart.MultipartOcclusionHelper.testContainerBoxIntersection(MultipartOcclusionHelper.java:28)
	at mod.chiselsandbits.integration.mcmultipart.ChiseledBlockPart.isBlobOccluded(ChiseledBlockPart.java:31)
	at mod.chiselsandbits.chiseledblock.TileEntityBlockChiseled.canMerge(TileEntityBlockChiseled.java:870)
	at mod.chiselsandbits.chiseledblock.ItemBlockChiseled.tryPlaceBlockAt(ItemBlockChiseled.java:355)
	at mod.chiselsandbits.core.ClientSide.showGhost(ClientSide.java:1372)
	at mod.chiselsandbits.core.ClientSide.doGhostForChiseledBlock(ClientSide.java:1261)
	at mod.chiselsandbits.core.ClientSide.drawLast(ClientSide.java:1212)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_23_ClientSide_drawLast_RenderWorldLastEvent.invoke(.dynamic)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:90)
	at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:179)
	at net.minecraftforge.client.ForgeHooksClient.dispatchRenderLast(ForgeHooksClient.java:160)
	at net.minecraft.client.renderer.EntityRenderer.func_175068_a(EntityRenderer.java:1430)
	at net.minecraft.client.renderer.EntityRenderer.func_78471_a(EntityRenderer.java:1259)
	at net.minecraft.client.renderer.EntityRenderer.func_181560_a(EntityRenderer.java:1062)
	at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:1117)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:397)
	at net.minecraft.client.main.Main.main(SourceFile:123)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.multimc.onesix.OneSixLauncher.launchWithMainClass(OneSixLauncher.java:236)
	at org.multimc.onesix.OneSixLauncher.launch(OneSixLauncher.java:297)
	at org.multimc.EntryPoint.listen(EntryPoint.java:162)
	at org.multimc.EntryPoint.main(EntryPoint.java:53)


A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Client thread
Stacktrace:
	at mcmultipart.api.multipart.MultipartHelper.getContainer(MultipartHelper.java:90)
	at mcmultipart.api.multipart.MultipartOcclusionHelper.testContainerBoxIntersection(MultipartOcclusionHelper.java:33)
	at mcmultipart.api.multipart.MultipartOcclusionHelper.testContainerBoxIntersection(MultipartOcclusionHelper.java:28)
	at mod.chiselsandbits.integration.mcmultipart.ChiseledBlockPart.isBlobOccluded(ChiseledBlockPart.java:31)
	at mod.chiselsandbits.chiseledblock.TileEntityBlockChiseled.canMerge(TileEntityBlockChiseled.java:870)
	at mod.chiselsandbits.chiseledblock.ItemBlockChiseled.tryPlaceBlockAt(ItemBlockChiseled.java:355)
	at mod.chiselsandbits.core.ClientSide.showGhost(ClientSide.java:1372)
	at mod.chiselsandbits.core.ClientSide.doGhostForChiseledBlock(ClientSide.java:1261)
	at mod.chiselsandbits.core.ClientSide.drawLast(ClientSide.java:1212)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_23_ClientSide_drawLast_RenderWorldLastEvent.invoke(.dynamic)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:90)
	at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:179)
	at net.minecraftforge.client.ForgeHooksClient.dispatchRenderLast(ForgeHooksClient.java:160)
	at net.minecraft.client.renderer.EntityRenderer.func_175068_a(EntityRenderer.java:1430)
	at net.minecraft.client.renderer.EntityRenderer.func_78471_a(EntityRenderer.java:1259)
```

**Comment by Shenton** [comment]
I was having the same issue, trying to place a single pane other a RS cable with a positive chisel design crashed the game (it did not crash a dedicated server, just the client), and it will leave a ghost block after reloading the game.
Updating MCMP did not fix the issue, but removing waila (hwyla) fixed it.

**Comment by Renari** [comment]
I did not have hwyla installed, only JEI,  Chisels & Bits, Refined Storage
and MCMP.

**Comment by Shenton** [comment]
The versions of the diferents mods/client/forge if it can help.

Minecraft 1.12.2
Forge 14.23.0.2501
Chisel & Bits 14.8
MCMP 2.3.0
RS 1.5.18

**Comment by amadornes** [comment]
Oh boy, this is going to be fun to fix... I'll look into it tomorrow!
Edit: Maybe not today... Just got home and I really need to rest.

**Comment by amadornes** [comment]
The crash issue has been quite a headache to figure out and fix, but I think I've done it... A new build will be up on CF as soon as it's approved. Let me know if it works :)

**Comment by 5t0rmr1d3r** [comment]
Can you please build the latest version to work with all the  1.12 versions?

**Comment by raoulvdberge** [comment]
Tested and works fine for me. Thanks for fixing Amadornes, but I do suggest marking all 1.12 versions compatible indeed.

**Comment by amadornes** [comment]
I plan on pushing a new one out today, so I'll mark it as compatible with all 1.12 versions. I tried the jar in 1.12 and it complained it wasn't for the right version, so it needs to be built again with a new version range :)

**Comment by 5t0rmr1d3r** [comment]
great! thank you!

**Comment by 5t0rmr1d3r** [comment]
tried the 2.3.3 on 1.12.0 with latest forge 14.21.1.2443
when i try to place a chise&bits plate on a refined storage cable client crashes.
[crash-2017-10-09_10.12.53-client.txt](https://github.com/amadornes/MCMultiPart/files/1367894/crash-2017-10-09_10.12.53-client.txt)
after restarting the game there is a ghostblock where i tried to place the plate....

**Comment by amadornes** [comment]
I just realized the amount of things I'm assuming with this implementation... If you can try the latest experimental build from maven and let me know if it still happens, I'd greatly appreciate it :)

https://maven.amadorn.es/MCMultiPart2/MCMultiPart-exp/2.3.4_48/MCMultiPart-exp-2.3.4_48.jar

**Comment by 5t0rmr1d3r** [comment]
i'll try it tomorrow...

**Comment by 5t0rmr1d3r** [comment]
finaly i had time to test the experimental build, client crash is also there
[crash-2017-10-13_21.30.13-client.txt](https://github.com/amadornes/MCMultiPart/files/1383782/crash-2017-10-13_21.30.13-client.txt)
ghost block still there. but more anoying is the game crash...
![2017-10-13_21 36 16](https://user-images.githubusercontent.com/4589916/31563260-cb49359c-b04d-11e7-8c56-cf3f19677be7.png)

**Comment by amadornes** [comment]
I may've fixed it in the newest experimental build. Algo found something that could potentially be what's causing it.

Here's the new build: https://maven.amadorn.es/MCMultiPart2/MCMultiPart-exp/2.3.4_49/MCMultiPart-exp-2.3.4_49.jar

**Comment by 5t0rmr1d3r** [comment]
it seems to work now on client, haven't testet it on server.
![2017-10-14_11 02 07](https://user-images.githubusercontent.com/4589916/31574398-a2e590b6-b0be-11e7-84c1-a0f62c09b53d.png)

**Comment by brisingraerowing** [comment]
At least it seems to work now! This was bugging me no end! (No pun intended!)

**Comment by AmandaCameron** [comment]
Thought I'd chime in:

The crashes are much less frequent for me with the experimental build, however the blocks are becoming ghosts immediately after a world reload for me. :/

RS: 1.5.23
C&B: 14.9
MCMP: 2.3.4_49 ( Linked earlier in this issue )
Forge: 14.23.0.2551

*Edited*: Added forge version

**Comment by Kousuke-kun** [comment]
This bug also rotated all of my external storages near it to the East and made all of my Thermal ducts single blocks (disconnected).

It caused weird behaviors in that chunk. It seems that anything with an orientation is changed to orient Eastwards visually. Ducts and such is visually disjointed.

**Comment by Solairn** [comment]
So on a side note, due to this bug of creating ghost blocks, from C&B on RS cables. Is there anyway to fix the ghost block? I updated to the beta build, and the game isn't crashing anymore but the old ghost blocks are still there. Furthermore when I put new C&B covers on RS cables just the cover turns into a ghost block, not the cable also.

**Comment by dblsaiko** [comment]
@Kousuke-kun your bug actually looks more like #100, I had the same symptoms with my blocks.

**Comment by raoulvdberge** [comment]
The new C&B build works around this problem, while we're waiting for a fix MCMP side.

**Comment by shikyo13** [comment]
I am currently running C&B 14.11 with MCMP 2.3.3 and still having the ghost block issue issue. Would love for a fix from MCMP on this. Thanks for all the work you guys do, love the mods!

**Comment by asiekierka** [comment]
The latest PR I sent should help with this.

**Comment by raoulvdberge** [comment]
Fixed..
